# Site settings
title: yanggb's Blog
url: "http://littlesev.github.io"    # the protocol and hostname of your site, eg. `http://littlesev.github.io`
baseurl: "/" # the prefix of your site uri, eg. `"/jekyll-theme-EasyBook"` or empty string `""`
#timezone: Asia/Chongqing
description: >
    the one that you love, died a long time ago.
#  One or more sentences introducing this blog.

# Your information
email: 203326278@qq.com
author: yanggb
avatar: "http://www.gravatar.com/avatar/203326278@qq.com_md5?d=mm&s=135"
#profile: One sentence introducing yourself.
#twitter_username: twitter_username
github_username:  littlesev
profile_links:
  Email: "203326278@qq.com"
  GitHub: "https://github.com/littlesev/littlesev.github.io"
  # You can add more profile links above, or edit _includes/sidebar.html 

# Comment Service (Disqus or 多说)
#  choose one and un-comment the line to active it
#disqus_shortname: xxx   # get one: https://disqus.com/admin/signup/
#duoshuo_shortname: xxx  # get one: http://duoshuo.com/create-site/

excerpt_separator: <!--more-->

header:
  links:             # Links on the header. Link to in-site page with a slash as prefix
    About: /about/
    Category: /category/
    #Donate: https://laobubu.net/donate.html

permalink: /archivers/:title
plugins:
 - jekyll-paginate
 - jekyll-gist
 - jemoji

# Build settings
paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

# https://jekyllrb.com/docs/configuration/#precedence
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

kramdown:
  input: GFM
  syntax_highlighter: rouge
  math_engine: mathjax
